name: Push

on:
  push:
    branches: [staging]

jobs:
  scout-import-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Install MySQL client
        run: sudo apt-get update && sudo apt-get install mysql-client
      - name: Run MySQL client
        run: sudo service mysql start

      - name: Run SQL script
        run: |
          mysql -h 127.0.0.1 -u root -p'root' -e "CREATE DATABASE test;"
