name: Push

on:
  push:
    branches: [staging]

jobs:
  scout-import-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --default-authentication-plugin=mysql_native_password
          --character-set-server=utf8mb4
          --collation-server=utf8mb4_unicode_ci

    steps:
      - name: Install MySQL client
        run: sudo apt-get update && sudo apt-get install mysql-client

      - name: Run SQL script
        run: |
          mysql -h 127.0.0.1 -u root -p'root' -e "CREATE DATABASE 'test';"
